### PR TITLE
Sync CSS with core

### PR DESCRIPTION
**Pull request by timja**
Dark theme:

<details>
<summary>Before</summary>

image

image

</details>

<details>
<summary>After</summary>

image

image

image

</details>

cc @jvz @fqueiruga

### CODE REVIEW

**Review by fqueiruga — APPROVED** [review]
First time I hear about this project. I though the secretTextarea was a Jenkins core widget

**Comment by jvz** [comment]
This library only exists as a migration point while we were waiting for `secretTextarea` to land in an LTS version of Jenkins. As it was developed originally as a security patch, we created this library and simultaneously added it to Jenkins Core in a weekly release. Are there any plugins still using this?

**Review by jvz — CHANGES_REQUESTED** [review]
This would either need to still work for old versions or needs some sort of updated docs and pom.xml referring to the proper baseline version of Jenkins.

**Comment by timja** [comment]
> This library only exists as a migration point while we were waiting for `secretTextarea` to land in an LTS version of Jenkins. As it was developed originally as a security patch, we created this library and simultaneously added it to Jenkins Core in a weekly release. Are there any plugins still using this?

yes github-branch-source is using it, not sure about others, this still works for old versions of Jenkins.

**Comment by timja** [comment]
Alternative fix would be to bump github-branch-source to the next LTS, it's currently on 2.164...

**Comment by jvz** [comment]
Basically, this library is as standalone as possible. I'm not sure how an updated dependency on this lib over there at gbs would help.

**Comment by timja** [comment]
If GitHub branch source goes to the next lts it can remove this dep

**Comment by timja** [comment]
Alternative https://github.com/jenkinsci/github-branch-source-plugin/pull/319

**Pull request closed without merging**
